version: "3"

services:
  database:
    container_name: portfolio_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_USER=portfolio
      - POSTGRES_DB=portfoliorhsm
    ports:
      - 5434:5432